### ISSUE TITLE
Show the  created Classes data send to the dashboard template  in a tabular form. The table should be searchable and filterable.

### ISSUE THREAD

**Issue by OliverMensahDev** [Brightfield-Tech-Academy/FullstackCohort1-Projects#45]
to retrieve all created Classes in the classes tables from the database

**Comment by CobbyElsonfx** [comment]
Please , am still waiting for Richmond created methods to be merged , so that i can pull it and use the method names in the Dashboard   filterable-class-table before pushing it , without  having it locally  its gonna give me undefined variable name.

**Comment by OliverMensahDev** [comment]
I think he did all the work. Check this PR he made #46
