### ISSUE TITLE
Display the subjects being studied by the student based on the class. 

### ISSUE THREAD

**Issue by OliverMensahDev** [Brightfield-Tech-Academy/FullstackCohort1-Projects#48]
The current function `getStudentDetails(string $id)` returns the subjects as well. 
Show the details of the subjects under academic information

<img width="1326" alt="Screenshot 2022-12-23 at 1 58 53 PM" src="https://user-images.githubusercontent.com/10617656/209348048-5ae73e42-fd18-4885-8db4-ed5f74a108b0.png">

**Comment by Richmond-Andoh** [comment]
Alright
